[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "24"

[[redirects]]
  from = "/"
  to = "/fr"
  status = 302
  conditions = {Language = ["fr", "fr-BE", "fr-FR", "fr-CH"]}

[[redirects]]
  from = "/"
  to = "/nl"
  status = 302

[[redirects]]
  from = "/nl/doe-mee"
  to = "/nl/vrijwilliger"
  status = 301

[[redirects]]
  from = "/nl/doe-mee/*"
  to = "/nl/vrijwilliger"
  status = 301

[[redirects]]
  from = "/fr/participez"
  to = "/fr/benevole"
  status = 301

[[redirects]]
  from = "/fr/participez/*"
  to = "/fr/benevole"
  status = 301
